# Generated by Django 5.0.3 on 2024-03-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Birthday', models.DateField()),
                ('Nationality', models.CharField(max_length=100)),
                ('Identity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('glucose_blood', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=8)),
                ('personal_medical_history', models.TextField()),
                ('medications', models.TextField()),
                ('allergies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.personalinfo')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.testresult')),
            ],
        ),
    ]
