# Generated by Django 5.0.3 on 2024-04-15 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('ID1', models.CharField(max_length=30)),
                ('medical_record', models.TextField()),
                ('name2', models.CharField(max_length=100)),
                ('phone_number2', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=100)),
                ('ID2', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('progress', models.CharField(choices=[('Đang tiếp nhận', 'Đang tiếp nhận'), ('Đang chẩn đoán', 'Đang chẩn đoán'), ('Đang điều trị', 'Đang điều trị'), ('Xuất viện', 'Xuất viện')], max_length=20)),
                ('medical_department', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('blood_pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('heart_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('blood_test', models.CharField(max_length=100)),
                ('urinalysis', models.CharField(max_length=100)),
                ('conclusion', models.TextField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
