# Generated by Django 5.0.3 on 2024-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Avatar', models.FileField(upload_to='')),
                ('Role', models.CharField(max_length=15)),
                ('Certificate', models.CharField(max_length=255)),
                ('Specialize', models.JSONField(max_length=255)),
                ('Availablle', models.BooleanField()),
            ],
        ),
    ]
