# Generated by Django 5.0.3 on 2024-04-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_admin_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numbers', models.PositiveIntegerField()),
                ('expiry', models.DateField()),
                ('input_day', models.DateField()),
                ('output_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numbers', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('maintenance_history', models.ManyToManyField(to='main_app.maintenanceevent')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_equipments', models.ManyToManyField(to='main_app.medicalequipment')),
                ('medicines', models.ManyToManyField(to='main_app.medicine')),
            ],
        ),
    ]
