# Generated by Django 5.0.3 on 2024-04-14 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_maintenanceevent_medicine_medicalequipment_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numbers', models.PositiveIntegerField()),
                ('changeType', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='input_day',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='output_day',
        ),
    ]
